[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino

; Serial Monitor Setup
monitor_speed = 115200
monitor_filters = time, colorize

; Library Dependencies
lib_deps =
    dlloydev/QuickPID @ ^3.1.9
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5

; Optimization (Recommended for real-time control)
build_flags = 
    -O2 
    -D NANO_33_BLE