; PlatformIO Project Configuration File
; --- Master Configuration for VCS V1.4 ---
[platformio]
default_envs = nano33ble

; 1. The Primary Target (Arduino Nano 33 BLE)
[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
lib_ldf_mode = deep+
lib_deps = 
	dlloydev/QuickPID
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SSD1306
upload_protocol = sam-ba

; 2. The Generic Target (Classic Arduino Nano - ATmega328P)
[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_ldf_mode = deep+
lib_deps = 
	dlloydev/QuickPID
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SSD1306