[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    dlloydev/QuickPID @ ^3.1.9
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit BusIO @ ^1.14.1

build_flags = 
    -D CORE_DEBUG_LEVEL=0 ; Set to 3 for debugging UART/I2C issues